SET SCHEMA PUBLIC
INSERT INTO COUNTRY (NAME) VALUES ('SPAIN',1)
INSERT INTO CITY (NAME, COUNTRY_ID) VALUES ('MADRID', 1)
INSERT INTO CITY (NAME, COUNTRY_ID) VALUES ('BARCELONA', 1)
INSERT INTO HOTEL (NAME, METERSTOCITYCENTER, CITY_ID) VALUES('HILTON', 126, 1)
INSERT INTO HOTEL (NAME, METERSTOCITYCENTER, CITY_ID) VALUES('NH', 235, 1)
INSERT INTO HOTEL (NAME, METERSTOCITYCENTER, CITY_ID) VALUES('NH', 235, 2)